version: "3.8"

services:
    fpm:
        build:
            context: .
            dockerfile: docker/php-fpm.Dockerfile
        volumes:
            - ./:/var/www/patreon
        links:
            - patreon-mysql
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/nginx.Dockerfile
        volumes:
            - ./:/var/www/patreon
        ports:
            - "8050:80"
        links:
            - fpm
    patreon-mysql:
        image: mysql
        container_name: patreon-mysql
        env_file:
            - .env
        ports:
            - "3002:3306"
        volumes:
            - ./data:/var/lib/mysql
