version: "3.8"

services:
    fpm:
        build:
            context: .
            dockerfile: docker/php-fpm.Dockerfile
        volumes:
            - ./:/var/www/patreon
        links:
            - patreon-mysql
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/nginx.Dockerfile
        volumes:
            - ./:/var/www/patreon
        ports:
            - "8050:80"
        links:
            - fpm
    patreon-mysql:
        image: mysql
        container_name: patreon-mysql
        env_file:
            - .env
        ports:
            - "3002:3306"
        volumes:
            - ./data:/var/lib/mysql
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - "9092:9092"
    kafdrop:
        image: obsidiandynamics/kafdrop
        ports:
            - "9000:9000"
        environment:
            KAFKA_BROKERCONNECT: kafka:19092
        depends_on:
            - kafka
